server:
  port: 8081
spring:
  thymeleaf:
    prefix: file:src/main/resources/templates/
    cache: false
  datasource:
    url: jdbc:mysql://localhost:3306/mafia?useUnicode=yes&characterEncoding=UTF-8
    username: root
    password: 1236
  jpa:
    hibernate:
      ddl-auto: update
